server:
  port: 8080
  
#db settings
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/butterfly?useUnicode:true&characterEncoding:utf-8&useSSL:false
    username: root
    password: t1e2s3t4
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 5Mb


# 忽略鉴权url
ignored:
  urls:
    - /menu/getAllList
    - /user/regist
    - /common/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico

butterfly:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10